# 02 · Build historical features
Pre-send features for every historical assignment. **Grain:** one row per `assignment_id`.
**Cutoff:** event ts `< send_ts`; windows are `[send_ts - N days, send_ts)`. Feature logic lives in `src/features.py`
so Step 07 can rebuild identical features at `policy_as_of_ts` (inclusive).
**Input:** Step 01 clean core tables. **Output:** `data/processed/historical_features.{csv,parquet}`, `feature_schema.csv`.

## Load Step 01 clean tables

In [1]:
import sys
from pathlib import Path
sys.path.insert(0, str(Path.cwd().parent))
import numpy as np, pandas as pd
from src.common import TABLES, load_clean, save
from src.features import build_features, FAMILIES, FEATURES, CATEGORICAL
pd.set_option("display.width", 200); pd.set_option("display.max_columns", 50)
t = load_clean()
spine = t["historical_assignments"]
CONTEXT = ["assignment_id", "customer_id", "campaign_id", "send_ts", "assignment_source", "offer_type", "email_delivered"]
print(spine.shape, spine.assignment_id.is_unique)

(26600, 7) True

## Build features

In [2]:
feats, audit = build_features(spine, t, key="assignment_id", cut="send_ts", inclusive=False)
hf = spine[CONTEXT].merge(feats.drop(columns=["customer_id", "send_ts"]), on="assignment_id", how="left", validate="1:1")
print(hf.shape, "| unique assignment_id:", hf.assignment_id.is_unique)

(26600, 50) | unique assignment_id: True

## Leakage test 1 — max (event_ts − send_ts) per feature family must be < 0

In [3]:
lk = pd.Series({k: v / pd.Timedelta(hours=1) for k, v in audit.items()}, name="max_event_minus_send_hours")
print(lk.round(2).to_dict())
assert (lk < 0).all(), "post-send event used in a feature"

{'purchase': -132.77, 'purchase_refunds': -3.67, 'prior_assignments': -504.0, 'returns': -3.67, 'web': -0.47, 'email': -409.0}

## Leakage test 2 — perturbation: inject events at/after send_ts; features must not change

In [4]:
rng = np.random.default_rng(42)
samp = spine.sample(frac=1, random_state=42).drop_duplicates("customer_id").head(400)
prior_o = samp.merge(t["orders"], on="customer_id").query("order_ts < send_ts").drop_duplicates("assignment_id")
tp = {k: v.copy() for k, v in t.items()}
s_ts = samp.send_ts + pd.to_timedelta(rng.integers(0, 14 * 24, len(samp)), unit="h")
n = len(samp)
fake_o = pd.DataFrame({"order_id": [f"FAKE{i}" for i in range(n)], "customer_id": samp.customer_id.values, "order_ts": s_ts.values,
                       "campaign_id": samp.campaign_id.values, "order_source": "campaign_attributed", "order_status": "completed",
                       "offer_redeemed": 1, "offer_type_redeemed": "PCT_10", "merchandise_gross_revenue": 999.0,
                       "discount_amount": 99.9, "shipping_revenue": 0.0, "net_revenue": 899.1, "cogs": 500.0,
                       "shipping_cost": 9.0, "is_completed": True})
tp["orders"] = pd.concat([tp["orders"], fake_o], ignore_index=True)
tp["order_items"] = pd.concat([tp["order_items"], pd.DataFrame({"order_id": fake_o.order_id, "line_number": 1,
                               "product_id": "CLM_001", "quantity": 5, "unit_list_price": 199.8, "unit_cost": 100.0})])
tp["returns"] = pd.concat([tp["returns"], pd.DataFrame({"return_id": [f"RF{i}" for i in range(len(prior_o))], "order_id":
                           prior_o.order_id.values, "return_ts": prior_o.send_ts.values, "refund_amount": 50.0,
                           "return_reason": "Other"})])
tp["web_sessions"] = pd.concat([tp["web_sessions"], pd.DataFrame({"session_id": [f"SF{i}" for i in range(n)], "customer_id":
                                pd.array(samp.customer_id.values, dtype="Int64"), "session_ts": samp.send_ts.values,
                                "device_type": "mobile", "pages_viewed": 15, "added_to_cart": 1, "category_viewed": "Climbing",
                                "traffic_source": "email", "is_identified": True})])
tp["email_events"] = pd.concat([tp["email_events"], pd.DataFrame({"email_event_id": [f"EF{i}" for i in range(n)], "assignment_id":
                                samp.assignment_id.values, "customer_id": samp.customer_id.values, "campaign_id":
                                samp.campaign_id.values, "event_ts": s_ts.values, "event_type": "click"})])
f_pert, _ = build_features(samp, tp)
f_base = feats.set_index("assignment_id").loc[samp.assignment_id].reset_index()
pd.testing.assert_frame_equal(f_base[FEATURES].reset_index(drop=True), f_pert[FEATURES].reset_index(drop=True))
print("perturbation test PASS: injected post-send orders/returns/sessions/email events left all features unchanged")

perturbation test PASS: injected post-send orders/returns/sessions/email events left all features unchanged

## Leakage test 3 — current-assignment outcomes never enter features

In [5]:
first = hf[hf.campaign_id == "CP01"]
assert (first[["prior_emails_delivered", "prior_email_opens", "prior_email_clicks"]] == 0).all().all()
assert first.prior_offer_redemption_rate.isna().all()
print("CP01 rows have zero prior email history and no prior redemption history: PASS")

CP01 rows have zero prior email history and no prior redemption history: PASS

## Sanity checks

In [6]:
assert hf.assignment_id.is_unique and len(hf) == len(spine)
assert hf.customer_tenure_days.ge(0).all()
fam = pd.Series({k: len(v) for k, v in FAMILIES.items()}, name="n_features")
print(fam.to_dict(), "| total:", fam.sum())
hf[FEATURES].describe(include="all").T[["count", "mean", "min", "max"]].head(45)

{'profile': 8, 'purchase': 13, 'returns': 3, 'web': 8, 'email': 7, 'product': 4} | total: 43

                               count        mean        min          max
customer_tenure_days         26600.0  632.789825  26.416667  1236.416667
is_member                    26600.0    0.281316        0.0          1.0
marketing_consent            26600.0         1.0        1.0          1.0
region                         26600         NaN        NaN          NaN
acquisition_channel            26371         NaN        NaN          NaN
customer_tier                  26600         NaN        NaN          NaN
preferred_category             26245         NaN        NaN          NaN
shipping_zone                  26600         NaN        NaN          NaN
prior_order_count            26600.0     0.36688        0.0          6.0
orders_30d                   26600.0    0.047895        0.0          2.0
orders_90d                   26600.0    0.153722        0.0          3.0
days_since_last_order         7591.0  108.893255   5.531944   324.078472
gross_revenue_90d            26600.0   58.349011        0.0      3454.69
net_revenue_90d              26600.0    56.03802        0.0      2935.53
avg_order_value_90d           3700.0  364.946384      13.22      2171.45
discount_amount_90d          26600.0     2.39229        0.0       519.16
cogs_90d                     26600.0   32.046903        0.0      1880.35
shipping_revenue_90d         26600.0    0.081293        0.0        11.98
shipping_cost_90d            26600.0    1.378606        0.0         31.7
historical_ncm_90d           26600.0   18.836225    -637.34       1086.6
prior_offer_redemption_rate  13061.0    0.116687        0.0          1.0
returns_90d                  26600.0    0.015977        0.0          2.0
refund_amount_90d            26600.0    4.507883        0.0       1198.7
historical_return_rate        7591.0    0.092842        0.0          1.0
sessions_7d                  26600.0    0.024586        0.0          3.0
sessions_30d                 26600.0    0.108684        0.0          3.0
pages_viewed_30d             26600.0    0.445376        0.0         20.0
avg_pages_per_session_30d     2648.0    4.088494        1.0         15.0
cart_add_sessions_30d        26600.0    0.041466        0.0          3.0
cart_add_rate_30d             2648.0    0.377706        0.0          1.0
days_since_last_session      13762.0  106.128142   0.019444   323.989583
top_category_viewed_30d         2648         NaN        NaN          NaN
prior_emails_delivered       26600.0    0.990188        0.0          6.0
prior_email_opens            26600.0    0.529812        0.0          6.0
prior_email_clicks           26600.0    0.191203        0.0          4.0
historical_open_rate         15765.0    0.534545        0.0          1.0
historical_click_rate        15765.0    0.194559        0.0          1.0
days_since_last_email_open   10538.0   46.338209  18.041667   125.958333
days_since_last_email_click   4517.0   51.250507  17.041667      125.875
units_purchased_90d          26600.0    0.408195        0.0         13.0
distinct_products_90d        26600.0    0.356842        0.0         10.0
distinct_categories_90d      26600.0    0.292481        0.0          6.0
top_purchase_category_90d       3700         NaN        NaN          NaN

In [7]:
hf.sample(3, random_state=0).T

                                           23076                6084                 5740
assignment_id                         A000023077           A000006085           A000005741
customer_id                               101406               107650               107890
campaign_id                                 CP07                 CP02                 CP02
send_ts                      2025-05-21 10:00:00  2025-02-05 10:00:00  2025-02-05 10:00:00
assignment_source                  business_rule        business_rule        business_rule
offer_type                              NO_OFFER               PCT_10               PCT_10
email_delivered                                1                    1                    1
customer_tenure_days                 1103.416667           944.416667           709.416667
is_member                                      0                    0                    0
marketing_consent                              1                    1                    1
region                                     South                 West                 West
acquisition_channel                    Affiliate             Referral              Organic
customer_tier                           Standard             Standard             Standard
preferred_category                      Climbing          Accessories          Accessories
shipping_zone                             Zone_3               Zone_3               Zone_4
prior_order_count                            1.0                  0.0                  0.0
orders_30d                                   0.0                  0.0                  0.0
orders_90d                                   1.0                  0.0                  0.0
days_since_last_order                  79.307639                  NaN                  NaN
gross_revenue_90d                          871.5                  0.0                  0.0
net_revenue_90d                            871.5                  0.0                  0.0
avg_order_value_90d                        871.5                  NaN                  NaN
discount_amount_90d                          0.0                  0.0                  0.0
cogs_90d                                  468.24                  0.0                  0.0
shipping_revenue_90d                         0.0                  0.0                  0.0
shipping_cost_90d                          14.19                  0.0                  0.0
historical_ncm_90d                        389.07                  0.0                  0.0
prior_offer_redemption_rate                  0.0                  NaN                  0.0
returns_90d                                  0.0                  0.0                  0.0
refund_amount_90d                            0.0                  0.0                  0.0
historical_return_rate                       0.0                  NaN                  NaN
sessions_7d                                  0.0                  0.0                  0.0
sessions_30d                                 0.0                  0.0                  0.0
pages_viewed_30d                             0.0                  0.0                  0.0
avg_pages_per_session_30d                    NaN                  NaN                  NaN
cart_add_sessions_30d                        0.0                  0.0                  0.0
cart_add_rate_30d                            NaN                  NaN                  NaN
days_since_last_session                      NaN                  NaN                  NaN
top_category_viewed_30d                      NaN                  NaN                  NaN
prior_emails_delivered                       4.0                  0.0                  1.0
prior_email_opens                            1.0                  0.0                  0.0
prior_email_clicks                           1.0                  0.0                  0.0
historical_open_rate                        0.25                  NaN                  0.0
historical_click_rate                       0.25                  NaN                  0.0
days_since_last_email_open             41.708333                  NaN                  NaN
days_since_last_email_click            41.416667                  NaN                  NaN
units_purchased_90d                          4.0                  0.0                  0.0
distinct_products_90d                        3.0                  0.0                  0.0
distinct_categories_90d                      3.0                  0.0                  0.0
top_purchase_category_90d                Camping                  NaN                  NaN

## Save output + feature schema
Profile fields have no effective-date history; they are treated as descriptors available at decision time (documented assumption).
`products.return_rate_prior` is excluded (time provenance undocumented). `email_delivered` is context, not a feature.

In [8]:
save(hf, "historical_features")
schema = pd.DataFrame([{"feature": f, "family": k, "type": "categorical" if f in CATEGORICAL else "numeric"}
                       for k, v in FAMILIES.items() for f in v])
schema = pd.concat([pd.DataFrame({"feature": CONTEXT, "family": "context", "type": "id/context (not a predictor)"}), schema])
schema.to_csv(TABLES / "feature_schema.csv", index=False)
print("saved historical_features", hf.shape)

saved historical_features (26600, 50)